steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud compute ssh --zone $_ZONE cloudbuild@$_INSTANCE_NAME --command '
        sudo su niteshshewale6@instance -c "cd $_PATH_TO_FOLDER && sudo mkdir sample"'
    entrypoint: /bin/bash




