steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Connect to instance
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      mkdir -p ~/root/.ssh && \\
      gcloud secrets versions access latest --secret=ec2_private > ~/root/.ssh/id_rsa && \\
      chmod 600 ~/root/.ssh/id_rsa && \\
      gcloud secrets versions access latest --secret=ec2_key > ~/root/.ssh/id_rsa.pub && \\
      chmod 600 ~/root/.ssh/id_rsa.pub && \\
      set -x && \\
     #gcloud compute ssh instance-1 --ssh-key-file=~/root/.ssh/id_rsa.pub --zone=asia-south1-c
      gcloud compute ssh instance-1 --zone=asia-south1-c --project=affable-beaker-407007
      nginx -v
