steps:
  # Step 1: Fetch the SSH private key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo -n "$(gcloud secrets versions access latest --secret=ec2_key)" > /workspace/pub-key
        chmod 600 /workspace/pub-key

  # Step 2: SSH into the GCP VM
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'instance-1'
      - '--zone=asia-south1-c'
      - '--project=affable-beaker-407007'
      - '--ssh-key-file=/workspace/pub-key'
      - '--command=cat /etc/os-release'  # Replace with your desired command
         
      
