substitutions:
  _INSTANCE_NAME: instance-1
  _PATH_TO_FOLDER: /var/www/
  _BRANCH: main
  _CUSTOM_ZONE: asia-south1-c
options:
  dynamic_substitutions: true
steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - >
        gcloud compute ssh --zone $_CUSTOM_ZONE cloudbuild@$_INSTANCE_NAME --command '
        sudo su -c "cd $_PATH_TO_FOLDER &&  mkdir demo"'
    entrypoint: /bin/bash
